FROM r-base

MAINTAINER mail@bla.com

RUN apt-get update
RUN apt-get -y install libpq-dev

RUN R -e 'install.packages("plumber")'
RUN R -e 'install.packages("RPostgreSQL")'

ADD database.R .

EXPOSE 8000

ENTRYPOINT ["R", "-e", "pr <- plumber::plumb(commandArgs()[4]); pr$run(port=8000)"]
CMD ["database.R"]
